spring:
  data:
    mongodb:
      database: gramf
aws:
  access.key: testkey
  secret.key: testkey
  bucket.name: testname

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true