spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:39AJqMeWd3LEznw@cluster0.s1ml9.mongodb.net/spotwalker?retryWrites=true&w=majority

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true